/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProjectionsRouteImport } from './routes/_authenticated/projections'
import { Route as AuthenticatedMilkRouteImport } from './routes/_authenticated/milk'
import { Route as AuthenticatedLivestockRouteImport } from './routes/_authenticated/livestock'
import { Route as AuthenticatedIncomeRouteImport } from './routes/_authenticated/income'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCropsRouteImport } from './routes/_authenticated/crops'
import { Route as AuthenticatedConstructionRouteImport } from './routes/_authenticated/construction'
import { Route as AuthenticatedAnimalsRouteImport } from './routes/_authenticated/animals'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedAnimalsIdRouteImport } from './routes/_authenticated/animals.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectionsRoute =
  AuthenticatedProjectionsRouteImport.update({
    id: '/projections',
    path: '/projections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMilkRoute = AuthenticatedMilkRouteImport.update({
  id: '/milk',
  path: '/milk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivestockRoute = AuthenticatedLivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncomeRoute = AuthenticatedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCropsRoute = AuthenticatedCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConstructionRoute =
  AuthenticatedConstructionRouteImport.update({
    id: '/construction',
    path: '/construction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnimalsRoute = AuthenticatedAnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnimalsIdRoute = AuthenticatedAnimalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAnimalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/animals': typeof AuthenticatedAnimalsRouteWithChildren
  '/construction': typeof AuthenticatedConstructionRoute
  '/crops': typeof AuthenticatedCropsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/livestock': typeof AuthenticatedLivestockRoute
  '/milk': typeof AuthenticatedMilkRoute
  '/projections': typeof AuthenticatedProjectionsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/animals/$id': typeof AuthenticatedAnimalsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/animals': typeof AuthenticatedAnimalsRouteWithChildren
  '/construction': typeof AuthenticatedConstructionRoute
  '/crops': typeof AuthenticatedCropsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/livestock': typeof AuthenticatedLivestockRoute
  '/milk': typeof AuthenticatedMilkRoute
  '/projections': typeof AuthenticatedProjectionsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/animals/$id': typeof AuthenticatedAnimalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/animals': typeof AuthenticatedAnimalsRouteWithChildren
  '/_authenticated/construction': typeof AuthenticatedConstructionRoute
  '/_authenticated/crops': typeof AuthenticatedCropsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/income': typeof AuthenticatedIncomeRoute
  '/_authenticated/livestock': typeof AuthenticatedLivestockRoute
  '/_authenticated/milk': typeof AuthenticatedMilkRoute
  '/_authenticated/projections': typeof AuthenticatedProjectionsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/animals/$id': typeof AuthenticatedAnimalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activities'
    | '/animals'
    | '/construction'
    | '/crops'
    | '/dashboard'
    | '/expenses'
    | '/income'
    | '/livestock'
    | '/milk'
    | '/projections'
    | '/projects'
    | '/statistics'
    | '/animals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activities'
    | '/animals'
    | '/construction'
    | '/crops'
    | '/dashboard'
    | '/expenses'
    | '/income'
    | '/livestock'
    | '/milk'
    | '/projections'
    | '/projects'
    | '/statistics'
    | '/animals/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activities'
    | '/_authenticated/animals'
    | '/_authenticated/construction'
    | '/_authenticated/crops'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/income'
    | '/_authenticated/livestock'
    | '/_authenticated/milk'
    | '/_authenticated/projections'
    | '/_authenticated/projects'
    | '/_authenticated/statistics'
    | '/_authenticated/animals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projections': {
      id: '/_authenticated/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof AuthenticatedProjectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/milk': {
      id: '/_authenticated/milk'
      path: '/milk'
      fullPath: '/milk'
      preLoaderRoute: typeof AuthenticatedMilkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livestock': {
      id: '/_authenticated/livestock'
      path: '/livestock'
      fullPath: '/livestock'
      preLoaderRoute: typeof AuthenticatedLivestockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/income': {
      id: '/_authenticated/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AuthenticatedIncomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crops': {
      id: '/_authenticated/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof AuthenticatedCropsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/construction': {
      id: '/_authenticated/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof AuthenticatedConstructionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/animals': {
      id: '/_authenticated/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AuthenticatedAnimalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/animals/$id': {
      id: '/_authenticated/animals/$id'
      path: '/$id'
      fullPath: '/animals/$id'
      preLoaderRoute: typeof AuthenticatedAnimalsIdRouteImport
      parentRoute: typeof AuthenticatedAnimalsRoute
    }
  }
}

interface AuthenticatedAnimalsRouteChildren {
  AuthenticatedAnimalsIdRoute: typeof AuthenticatedAnimalsIdRoute
}

const AuthenticatedAnimalsRouteChildren: AuthenticatedAnimalsRouteChildren = {
  AuthenticatedAnimalsIdRoute: AuthenticatedAnimalsIdRoute,
}

const AuthenticatedAnimalsRouteWithChildren =
  AuthenticatedAnimalsRoute._addFileChildren(AuthenticatedAnimalsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedAnimalsRoute: typeof AuthenticatedAnimalsRouteWithChildren
  AuthenticatedConstructionRoute: typeof AuthenticatedConstructionRoute
  AuthenticatedCropsRoute: typeof AuthenticatedCropsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedIncomeRoute: typeof AuthenticatedIncomeRoute
  AuthenticatedLivestockRoute: typeof AuthenticatedLivestockRoute
  AuthenticatedMilkRoute: typeof AuthenticatedMilkRoute
  AuthenticatedProjectionsRoute: typeof AuthenticatedProjectionsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedAnimalsRoute: AuthenticatedAnimalsRouteWithChildren,
  AuthenticatedConstructionRoute: AuthenticatedConstructionRoute,
  AuthenticatedCropsRoute: AuthenticatedCropsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedIncomeRoute: AuthenticatedIncomeRoute,
  AuthenticatedLivestockRoute: AuthenticatedLivestockRoute,
  AuthenticatedMilkRoute: AuthenticatedMilkRoute,
  AuthenticatedProjectionsRoute: AuthenticatedProjectionsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
